### ISSUE TITLE
Build for .NET 6.0 LTS

### ISSUE THREAD

**Issue by driverjb** [agracio/edge-js#146]
I really enjoy using this module since I am very familiar with JavaScript. However, I am currently using .NET 6.0 LTS for a project and it doesn't recognize the build for 4.5. Right now, I'm stuck learning Lua (NLua package) to provide embedded scripting support for my application.

Any chance you will provide a build that supports .NET 6?

**Comment by ruaumoko** [comment]
I too am interested to know if .NET 6.0 will be supported.  I have some precompiled libraries that were written with Core 1.0 (which work fine).  I've had some success with the same libraries complied with .NET 5.0; some as in works on some computers but not on others.  But I'd like to update them to .NET 6.0.  I expect there's more than just changing the target framework of my libraries to  .NET 6.0 ... or is there?

**Comment by ruaumoko** [comment]
Feeling that this project might not be going to keep going .. or at least slowing down.  I've been using edge-js as a bridge between Node and C#.  It's been good but I've been locked into precompiled DLLs that target .NET 1.x.  (Turns out my limited success with versions above .NET 1.x wasn't real.  I'd just not checked a few things in my configuration.)

(For anyone looking to build their own bridge between Node and some precompiled DLLs, I've had good success building a Node addon implementing the Node Addon API.  I've buried it beneath the C++/CLI which targets .NET 6.0.  There's a bit of a learning curve (especially for those not used to C++).  It's never going to do all the things that edge-js does but for my purposes it doesn't need to.  I'm just looking to call methods form precompiled .NET DLLs.  (A heads up for anyone else that heads in that direction ... If you're using VS2022 and you get a "Failed to create CoreCLR, HRESULT: 0x80070057" in your test output or console, it may not be your code.  Change your Platform Target ... and then change it back.  I don't know why it works but it took me days to figure this out.))
