### ISSUE TITLE
Is repo "tjanczuk/edge" deprecated

### ISSUE THREAD

**Issue by zd-dalibor** [agracio/edge-js#30]
Is repo [tjanczuk/edge](https://github.com/tjanczuk/edge) deprecated?

If this is true it will be nice to add some info that tjanczuk/edge repo is not in maintenance any more and put link to this repository.

**Comment by agracio** [comment]
tjanczuk has not provided any official update on this and as far as I know does not respond to messages. He simply abandoned the repo and set up and auto-reply to all new issues. Since he is active on his other projects he either lost interest in Edge.js or doesn't have the time for it. Regardless of his reasons it would have been good if he provided some kind of official statement.

**Comment by czema** [comment]
Is that why he reply Hello World! to everything?

**Comment by 0xF6** [comment]
Reason in slack
![image](https://user-images.githubusercontent.com/13326808/41488893-9c3a4fec-70f6-11e8-8311-223ee37b28e2.png)

**Comment by stephen776** [comment]
Would be awesome to get this repo merged into the "official" repo and continue from there with the two communities merged.

**Comment by 0xF6** [comment]
@stephen776,
Notify @tjanczuk in slack

**Comment by sandipbiswasbehala** [comment]
tjanczuk should continue...

**Comment by 0xF6** [comment]
maybe
