### ISSUE TITLE
Return promises from func invocations?

### ISSUE THREAD

**Issue by grofit** [agracio/edge-js#39]
I am just doing a spike using edge js and one thing I noticed odd is that it supports ES6 template literals for code, but doesnt seem to return/use ES6 promises from the `func` handlers returned?

i.e I would expect something like:

```ts
const handler = edge.func(`...`);
handler()
   .then(result => console.log("got", result))
   .catch(console.error);
```

If it returned a promise it also opens up use cases for async/await like:

```ts
const handler = edge.func(`...`);
const result = await handler();
```

Is there any technical reason why Promises are not used?

**Comment by agracio** [comment]
Not sure what you mean, `edge.func` is a standard JS function so it will not return a promise. You can wrap your calls in promises, there is no intention to support it natively in Edge.js

**Comment by grofit** [comment]
Yeah at the moment I just wrap the function call in a promise like so:

```js
const someFunction = () {
   const handler = edge.func(`...`);
   return new Promise((resolve, reject) => {
       handler((err, result) => {
           if(err) { reject(err); }
           else { resolve(result); }
        });
    });
}
```

Most modern JS libs have done way with callbacks that have err/result and move to a more sane `Promise` approach, as this allows bulk catching, and use with `await` allowing for more succinct code.

If you are now the main steward for this library I would advise at least looking into the subject of `Promises` if you are unsure what I am on about as there is very little down sides to you supporting them natively other than really old browsers and really old versions of node would need a polyfill, but as I say most JS libs these days use promises as a better solution to async functions which need to handle success/failure.

**Comment by agracio** [comment]
I am well aware of what promises are, but as noted in my previous comment there is currently no intention to add native promise support. Edge.js returns a single `edge.func` and is very simple to wrap as a promise in your app implementation.

**Comment by alfnielsen** [comment]
Are there still not any intention on making a edge.funcAsync (or what ever name) that returns a function with a promise instead of a function that takes a callback ? 

(Which prevent using async/await pattern..)
I believe its commonly agreed that async coding in C# uses Tasks and in Js/Ts uses Promises to enable better readable code with async/await pattern. 
Right now the edge.func's returned method require a callback instead of a returning promise !
(It seems strange that every body needs to wrap all there method in a promise to enable this)

It should be pretty easy to add, so I can make a PR to add this if that is of interest  ?
