### ISSUE TITLE
Node 12 DLL

### ISSUE THREAD

**Issue by davidhouweling** [agracio/edge-js#93]
I've been having difficulty compiling a node 12 dll.

Checking the node.dll that is bundled in to the latest nuget package, I can see it is still running 8.9.3. Is it possible to get the nuget package to contain the different node versions supported that we could pick more easily?

Or perhaps to have the node.dll at least hosted somewhere so that it can be considered a pre-compiled download, rather than needing to manually do it?

**Comment by agracio** [comment]
What would be the reason to include different versions of node.dll? It does not have any dependency on Node.js version installed on your system.

**Comment by davidhouweling** [comment]
At least from what I am seeing, my asp.net application is picking up the node.dll which is 8.9.3, but on my machine i've got node 12 installed on it. how would i go about getting it to use the installed node version instead of the dll?

**Comment by agracio** [comment]
1. Node.js install does not have node.dll that you could reference, nor does it have any packages that you can download with .dll version instead of .exe, besides when building .NET project you are unlikely to reference DLLs in Program Files folder. 
2. The point of nuget package is that it is part of your project and has no dependency on Node.js install on the target system, as I mentioned before Node.js install is not required. This is true for any nuget package that you use in .NET project, you do not use dlls scattered around the system.
3. Unless you can point to very specific improvements that would improve performance of your or perhaps more generic projects I see very little point in rebuilding Node,js for each version.

**Comment by davidhouweling** [comment]
Sure, i completely agree that we shouldn't be referencing dlls scattered throughout, which is why your nuget package contains the node.dll which gets copied into the application as content which is great.

The other reason to upgrade as well is that node runs on a relatively short LTS. Version 8's end of life is the end of this year (refer to https://github.com/nodejs/Release). So in that regard, come start of next year this package will be shipping with a version of node which is not maintained.

There are presently issues with compiling Node 12 on Windows unfortunately (refer to https://github.com/nodejs/node/issues/28845) but I have raised a PR to fix it. However, I did try the compiled version locally but my asp.net application just imploded (the call out to the dll made the application die, even when debugging).

This was the reason I originally raised this issue/request, as I also wanted to know exactly how node 12 was verified to be working, or was it only from node 12 to C# REPL, rather than C# to node 12?

**Comment by agracio** [comment]
> This was the reason I originally raised this issue/request, as I also wanted to know exactly how node 12 was verified to be working, or was it only from node 12 to C# REPL, rather than C# to node 12?
 I am not sure what you mean by this. Perhaps you are confusing the two main functions of Edge.js
1. Script CLR from Node.js - this part requires to recompile new versions of Node.js and the binaries are stored under `lib/native/win32`. When you working with Node.js to CLR interaction you do need to have Node installed and the version you have is the one that is used by your application.
2. Script Node.js from CLR - this is the one you are trying to use. It requires to fully recompile Node.js from source as dll rather than exe and is added to nuget package. Unlike option 1 it has no dependency on Node.js installation on machine and works as a standalone dll with no other dependencies, similar to any other dll that you install from nuget.

**Comment by davidhouweling** [comment]
Sorry I'll try and be more clear. I understand that there are 2 parts to Edge.js. I was wondering more how the second part was tested as code has been updated to say that newer versions of node is supported, but the standalone dll hasn't changed so I take it the mentioned changes were more for point 1 rather than point 2.

**Comment by agracio** [comment]
Newer version updates only relate to part 1. Part 2 is stale unless there are updates to the code that wraps it in order to work in CLR -> Node.js way.

**Comment by davidhouweling** [comment]
Ok. Thanks for letting me know. If I have time and do figure out what is wrong with the newer DLL I'll try and provide a PR with updated node DLL.
